# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgregadorCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_legado', models.IntegerField(unique=True)),
                ('data_ata', models.DateField()),
                ('numero_ata_conselho', models.IntegerField(unique=True)),
                ('identificacao', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='AtoOficial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_legado', models.IntegerField(unique=True)),
                ('data', models.DateField()),
                ('dados_ato', models.TextField()),
                ('detalhes', models.TextField()),
                ('dt_hora_legado', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_legado', models.IntegerField(unique=True)),
                ('descricao', models.CharField(max_length=32)),
                ('detalhes', models.CharField(max_length=64)),
                ('agregador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='rol.AgregadorCategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_legado', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=128)),
                ('cidade', models.CharField(max_length=64)),
                ('uf', models.CharField(max_length=4)),
                ('ipb', models.BooleanField()),
                ('nome_secretario_conselho', models.CharField(max_length=64)),
                ('email_secretario_conselho', models.CharField(max_length=128)),
                ('observacao', models.TextField()),
                ('endereco', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(unique=True)),
                ('dados_admissao', models.CharField(max_length=512)),
                ('rol_separado', models.BooleanField()),
                ('ata_admissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admitidos', to='rol.Ata')),
                ('ata_demissao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demitidos', to='rol.Ata')),
            ],
        ),
        migrations.CreateModel(
            name='Oficialato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_legado', models.IntegerField(unique=True)),
                ('cargo', models.CharField(max_length=64)),
                ('data_inicio_mandato', models.DateField()),
                ('data_fim_mandato', models.DateField()),
                ('ordenacao', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_legado', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=128)),
                ('apelido', models.CharField(max_length=32)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('comungante', models.BooleanField()),
                ('foto', models.CharField(max_length=1024)),
                ('data_nascimento', models.DateField()),
                ('data_falecimento', models.DateField(null=True)),
                ('entrevista_admissao_realizada', models.BooleanField()),
                ('carta_transferencia_requisitada', models.BooleanField()),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(max_length=30)),
                ('data_inicio_relacionamento', models.DateField(null=True)),
                ('batismo_quando', models.CharField(max_length=32)),
                ('batismo_onde', models.CharField(max_length=64)),
                ('profissao_fe_quando', models.CharField(max_length=32)),
                ('profissao_fe_onde', models.CharField(max_length=64)),
                ('razoes_pedido_admissao', models.TextField()),
                ('observacoes_legado', models.TextField()),
                ('data_pedido_admissao', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='rol.Categoria')),
                ('chefe_familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_da_familia', to='rol.Pessoa')),
                ('conjuge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_conjuge', to='rol.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAdmissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_legado', models.IntegerField(unique=True)),
                ('descricao', models.CharField(max_length=64)),
                ('relativo_a', models.CharField(choices=[('MNC', 'Membro Não Comungante'), ('MC', 'Membro Comungante')], max_length=3)),
                ('fonte', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoAto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_legado', models.IntegerField(unique=True)),
                ('descricao', models.CharField(max_length=64)),
                ('detalhes', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_legado', models.IntegerField(unique=True)),
                ('descricao', models.CharField(max_length=64)),
                ('detalhes', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDemissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_legado', models.IntegerField(unique=True)),
                ('descricao', models.CharField(max_length=64)),
                ('relativo_a', models.CharField(choices=[('MNC', 'Membro Não Comungante'), ('MC', 'Membro Comungante')], max_length=3)),
                ('fonte', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_legado', models.IntegerField(unique=True)),
                ('descricao', models.CharField(max_length=64)),
                ('detalhes', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='estado_civil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='rol.TipoEstadoCivil'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='forma_admissao_pretendida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='rol.TipoAdmissao'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='igreja_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='rol.Igreja'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filhos_m', to='rol.Pessoa'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='mae_biologica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos_biologicos_m', to='rol.Pessoa'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='pai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filhos_p', to='rol.Pessoa'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='pai_biologico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos_biologicos_p', to='rol.Pessoa'),
        ),
        migrations.AddField(
            model_name='oficialato',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficial', to='rol.Pessoa'),
        ),
        migrations.AddField(
            model_name='membro',
            name='forma_admissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='rol.TipoAdmissao'),
        ),
        migrations.AddField(
            model_name='membro',
            name='forma_demissao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ex_membros', to='rol.TipoDemissao'),
        ),
        migrations.AddField(
            model_name='membro',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membro', to='rol.Pessoa'),
        ),
        migrations.AddField(
            model_name='membro',
            name='transferido_para',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ex_membros', to='rol.Igreja'),
        ),
        migrations.AddField(
            model_name='contato',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rol.Pessoa'),
        ),
        migrations.AddField(
            model_name='contato',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rol.TipoContato'),
        ),
        migrations.AddField(
            model_name='atooficial',
            name='celebrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atos_oficiais_celebrados', to='rol.Pessoa'),
        ),
        migrations.AddField(
            model_name='atooficial',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atos_oficiais', to='rol.Pessoa'),
        ),
        migrations.AddField(
            model_name='atooficial',
            name='tipo_ato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atos_oficiais_realizados', to='rol.TipoAto'),
        ),
    ]
