# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='id_legado',
        ),
    ]
