# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0002_remove_categoria_id_legado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='detalhes',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
