# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0003_auto_20171007_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ata',
            name='id_legado',
        ),
        migrations.RemoveField(
            model_name='atooficial',
            name='id_legado',
        ),
        migrations.RemoveField(
            model_name='igreja',
            name='id_legado',
        ),
        migrations.RemoveField(
            model_name='oficialato',
            name='id_legado',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='id_legado',
        ),
        migrations.RemoveField(
            model_name='tipoadmissao',
            name='id_legado',
        ),
        migrations.RemoveField(
            model_name='tipoato',
            name='id_legado',
        ),
        migrations.RemoveField(
            model_name='tipocontato',
            name='id_legado',
        ),
        migrations.RemoveField(
            model_name='tipodemissao',
            name='id_legado',
        ),
        migrations.RemoveField(
            model_name='tipoestadocivil',
            name='id_legado',
        ),
    ]
