# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0005_auto_20171020_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='carta_transferencia_requisitada',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='comungante',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='entrevista_admissao_realizada',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
    ]
