# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0007_auto_20171020_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='carta_transferencia_requisitada',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='comungante',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='entrevista_admissao_realizada',
            field=models.NullBooleanField(),
        ),
    ]
