# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0008_auto_20171020_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoestadocivil',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='igreja',
            name='cidade',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='email_secretario_conselho',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='endereco',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='ipb',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='nome_secretario_conselho',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='observacao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='uf',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='membro',
            name='dados_admissao',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='membro',
            name='rol_separado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tipocontato',
            name='detalhes',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tipoestadocivil',
            name='detalhes',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
