# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0010_igreja_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoadmissao',
            name='fonte',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tipoadmissao',
            name='relativo_a',
            field=models.CharField(choices=[('MNC', 'Membro Não Comungante'), ('MC', 'Membro Comungante')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tipodemissao',
            name='fonte',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tipodemissao',
            name='relativo_a',
            field=models.CharField(choices=[('MNC', 'Membro Não Comungante'), ('MC', 'Membro Comungante')], max_length=3, null=True),
        ),
    ]
