# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0011_auto_20171102_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficialato',
            name='data_fim_mandato',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='oficialato',
            name='data_inicio_mandato',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='oficialato',
            name='ordenacao',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
