# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0012_auto_20171102_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocontato',
            name='desc_legado',
            field=models.CharField(default='default', max_length=64),
            preserve_default=False,
        ),
    ]
