# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0013_tipocontato_desc_legado'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='usa_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parente', to='rol.Pessoa'),
        ),
    ]
