# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0014_contato_usa_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoato',
            name='precedente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ato_precedente', to='rol.TipoAto'),
        ),
    ]
