# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0015_tipoato_precedente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ata',
            old_name='data_ata',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='ata',
            name='numero_ata_conselho',
        ),
        migrations.AddField(
            model_name='tipoato',
            name='presbiterio',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='ata',
            name='identificacao',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoato',
            name='descricao',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tipoato',
            name='detalhes',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
