# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0016_auto_20171212_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='agregador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='categorias', to='rol.AgregadorCategoria'),
        ),
    ]
