# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0017_auto_20171212_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atooficial',
            name='celebrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='atos_oficiais_celebrados', to='rol.Pessoa'),
        ),
        migrations.AlterField(
            model_name='atooficial',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='atos_oficiais', to='rol.Pessoa'),
        ),
        migrations.AlterField(
            model_name='atooficial',
            name='tipo_ato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='atos_oficiais_realizados', to='rol.TipoAto'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rol.Pessoa'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rol.TipoContato'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='usa_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parente', to='rol.Pessoa'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='ata_admissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='admitidos', to='rol.Ata'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='ata_demissao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='demitidos', to='rol.Ata'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='forma_admissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='membros', to='rol.TipoAdmissao'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='forma_demissao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ex_membros', to='rol.TipoDemissao'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='transferido_para',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ex_membros', to='rol.Igreja'),
        ),
        migrations.AlterField(
            model_name='oficialato',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='oficial', to='rol.Pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pessoas', to='rol.Categoria'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='chefe_familia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='membros_da_familia', to='rol.Pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='conjuge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pessoa_conjuge', to='rol.Pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='estado_civil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pessoas', to='rol.TipoEstadoCivil'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='forma_admissao_pretendida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pessoas', to='rol.TipoAdmissao'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='igreja_origem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pessoas', to='rol.Igreja'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='mae',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='filhos_m', to='rol.Pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='mae_biologica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='filhos_biologicos_m', to='rol.Pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='filhos_p', to='rol.Pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pai_biologico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='filhos_biologicos_p', to='rol.Pessoa'),
        ),
        migrations.AlterField(
            model_name='tipoato',
            name='precedente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ato_precedente', to='rol.TipoAto'),
        ),
    ]
