# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0018_auto_20171212_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='membro', to='rol.Pessoa'),
        ),
    ]
