# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0019_auto_20171212_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='atooficial',
            name='ata_ato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ata_do_ato', to='rol.Ata'),
        ),
        migrations.AlterField(
            model_name='atooficial',
            name='celebrante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='atos_oficiais_celebrados', to='rol.Pessoa'),
        ),
        migrations.AlterField(
            model_name='atooficial',
            name='dados_ato',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='atooficial',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='atooficial',
            name='detalhes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='atooficial',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='atos_oficiais', to='rol.Pessoa'),
        ),
        migrations.AlterField(
            model_name='atooficial',
            name='tipo_ato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='atos_oficiais_realizados', to='rol.TipoAto'),
        ),
    ]
