# Generated by Django 2.0 on 2018-01-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0021_auto_20171215_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='nome_ascii',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
