# Generated by Django 2.0 on 2018-01-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0022_pessoa_nome_ascii'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocontato',
            name='desc_sistema',
            field=models.CharField(default='txt', max_length=64),
            preserve_default=False,
        ),
    ]
