# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0023_tipocontato_desc_sistema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
