# Generated by Django 2.0.1 on 2018-01-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0027_auto_20180131_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='naturalidade',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
