# Generated by Django 2.0 on 2018-02-03 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0028_pessoa_naturalidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ata',
            options={'ordering': ['identificacao']},
        ),
        migrations.AlterModelOptions(
            name='atooficial',
            options={'ordering': ['tipo_ato', 'pessoa']},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['descricao']},
        ),
        migrations.AlterModelOptions(
            name='igreja',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='membro',
            options={'ordering': ['matricula']},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['nome_ascii']},
        ),
        migrations.AlterModelOptions(
            name='tipoadmissao',
            options={'ordering': ['descricao']},
        ),
        migrations.AlterModelOptions(
            name='tipoato',
            options={'ordering': ['descricao']},
        ),
        migrations.AlterModelOptions(
            name='tipocontato',
            options={'ordering': ['descricao']},
        ),
        migrations.AlterModelOptions(
            name='tipodemissao',
            options={'ordering': ['descricao']},
        ),
        migrations.AlterModelOptions(
            name='tipoestadocivil',
            options={'ordering': ['descricao']},
        ),
        migrations.AddField(
            model_name='membro',
            name='invalido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membro',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='membro', to='rol.Pessoa'),
        ),
    ]
