# Generated by Django 2.0 on 2018-02-05 18:25

from django.db import migrations, models
import django.db.models.deletion
import rol.models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0029_auto_20180203_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atooficial',
            name='ata_ato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ata_do_ato', to='rol.Ata'),
        ),
        migrations.AlterField(
            model_name='atooficial',
            name='celebrante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='atos_oficiais_celebrados', to='rol.Pessoa'),
        ),
        migrations.AlterField(
            model_name='atooficial',
            name='dados_ato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atooficial',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atooficial',
            name='detalhes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atooficial',
            name='dt_hora_legado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atooficial',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='atos_oficiais', to='rol.Pessoa'),
        ),
        migrations.AlterField(
            model_name='atooficial',
            name='tipo_ato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='atos_oficiais_realizados', to='rol.TipoAto'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='detalhes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='usa_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parente', to='rol.Pessoa'),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='cidade',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='classe',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='email_secretario_conselho',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='endereco',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='nome_secretario_conselho',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='uf',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='membro',
            name='ata_demissao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='demitidos', to='rol.Ata'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='dados_admissao',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='membro',
            name='dados_demissao',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='membro',
            name='data_admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membro',
            name='data_demissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membro',
            name='forma_demissao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ex_membros_demitidos', to='rol.TipoDemissao'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='transferido_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ex_membros_transferidos', to='rol.Igreja'),
        ),
        migrations.AlterField(
            model_name='oficialato',
            name='data_fim_mandato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oficialato',
            name='data_inicio_mandato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oficialato',
            name='ordenacao',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='apelido',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='batismo_onde',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='batismo_quando',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pessoas', to='rol.Categoria'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='chefe_familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='membros_da_familia', to='rol.Pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='conjuge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pessoa_conjuge', to='rol.Pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_falecimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_inicio_relacionamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_pedido_admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='estado_civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pessoas', to='rol.TipoEstadoCivil'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='forma_admissao_pretendida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pessoas', to='rol.TipoAdmissao'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=rol.models.Pessoa.pic_pessoa_id),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='igreja_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pessoas', to='rol.Igreja'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='mae',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='filhos_m', to='rol.Pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='mae_biologica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='filhos_biologicos_m', to='rol.Pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='naturalidade',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome_ascii',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='observacoes_legado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='filhos_p', to='rol.Pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pai_biologico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='filhos_biologicos_p', to='rol.Pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='profissao_fe_onde',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='profissao_fe_quando',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='razoes_pedido_admissao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='rg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tipoadmissao',
            name='fonte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipoadmissao',
            name='relativo_a',
            field=models.CharField(blank=True, choices=[('MNC', 'Membro Não Comungante'), ('MC', 'Membro Comungante')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tipoato',
            name='descricao',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tipoato',
            name='detalhes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tipoato',
            name='precedente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ato_precedente', to='rol.TipoAto'),
        ),
        migrations.AlterField(
            model_name='tipocontato',
            name='detalhes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tipodemissao',
            name='fonte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipodemissao',
            name='relativo_a',
            field=models.CharField(blank=True, choices=[('MNC', 'Membro Não Comungante'), ('MC', 'Membro Comungante')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tipoestadocivil',
            name='detalhes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
