# Generated by Django 2.0 on 2018-02-05 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0030_auto_20180205_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atooficial',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='atos_oficiais', to='rol.Pessoa'),
        ),
        migrations.AlterField(
            model_name='atooficial',
            name='tipo_ato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='atos_oficiais_realizados', to='rol.TipoAto'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=256),
        ),
    ]
