# Generated by Django 2.0 on 2018-02-06 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rol', '0031_auto_20180205_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='data_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='atualizado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
