# Generated by Django 2.0 on 2018-02-06 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0032_auto_20180206_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEstadoCivilComplemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
        migrations.RemoveField(
            model_name='tipoestadocivil',
            name='detalhes',
        ),
        migrations.RemoveField(
            model_name='tipoestadocivil',
            name='sexo',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nao_conjuge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pessoa_nao_conjuge', to='rol.Pessoa'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='estado_civil_complemento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pessoas', to='rol.TipoEstadoCivilComplemento'),
        ),
    ]
