# Generated by Django 2.0 on 2018-02-19 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0033_auto_20180206_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TurmaFrequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('dt_inicio', models.DateField()),
                ('dt_fim', models.DateField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=512)),
                ('tipo', models.CharField(choices=[('culto', 'Culto'), ('bercario', 'Berçário'), ('ebd', 'Escola Bíblica Dominical'), ('gf', 'Grupos Familiares'), ('si', 'Sociedades Internas'), ('outro', 'Outros Eventos')], max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='frequencia',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rol.TurmaFrequencia'),
        ),
    ]
