# Generated by Django 2.0 on 2018-03-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0034_auto_20180219_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='ata',
            name='numero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
