# Generated by Django 2.0 on 2018-03-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0035_auto_20180308_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ata',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='turmafrequencia',
            name='tipo',
            field=models.CharField(choices=[('culto', 'Culto'), ('bercario', 'Berçário'), ('ebd', 'Escola Bíblica Dominical'), ('ebd-infantil', 'Escola Bíblica Dominical Infantil'), ('gf', 'Grupos Familiares'), ('si', 'Sociedades Internas'), ('outro', 'Outros Eventos')], max_length=8),
        ),
    ]
