# Generated by Django 2.0 on 2018-03-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0037_auto_20180312_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rol.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='TipoGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='turmafrequencia',
            name='lideranca',
            field=models.ManyToManyField(related_name='lideranca', to='rol.Pessoa'),
        ),
        migrations.AddField(
            model_name='turmafrequencia',
            name='participantes',
            field=models.ManyToManyField(related_name='participantes', to='rol.Pessoa'),
        ),
        migrations.AlterField(
            model_name='turmafrequencia',
            name='tipo',
            field=models.CharField(choices=[('culto', 'Culto'), ('bercario', 'Berçário'), ('ebd', 'Escola Bíblica Dominical'), ('ebdi', 'Escola Bíblica Dominical Infantil'), ('gf', 'Grupos Familiares'), ('si', 'Sociedades Internas'), ('outro', 'Outros Grupos')], max_length=8),
        ),
        migrations.AddField(
            model_name='presenca',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rol.TurmaFrequencia'),
        ),
        migrations.AddField(
            model_name='turmafrequencia',
            name='tipo_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rol.TipoGrupo'),
        ),
    ]
