# Generated by Django 2.0 on 2018-03-15 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0040_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pessoas_rol', to='rol.Rol'),
            preserve_default=False,
        ),
    ]
