# Generated by Django 2.2.7 on 2019-11-12 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rol', '0041_pessoa_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['pk']},
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True)),
                ('comungante', models.NullBooleanField()),
                ('idade_minima', models.IntegerField(blank=True, null=True)),
                ('idade_maxima', models.IntegerField(blank=True, null=True)),
                ('data_falecimento_inicial', models.DateField(blank=True, null=True)),
                ('data_falecimento_final', models.DateField(blank=True, null=True)),
                ('entrevista_admissao_realizada', models.NullBooleanField()),
                ('carta_transferencia_requisitada', models.NullBooleanField()),
                ('data_inicio_relacionamento_inicial', models.DateField(blank=True, null=True)),
                ('data_inicio_relacionamento_final', models.DateField(blank=True, null=True)),
                ('data_pedido_admissao_inicial', models.DateField(blank=True, null=True)),
                ('data_pedido_admissao_final', models.DateField(blank=True, null=True)),
                ('tem_filhos', models.NullBooleanField()),
                ('data_admissao_inicial', models.DateField(blank=True, null=True)),
                ('data_admissao_final', models.DateField(blank=True, null=True)),
                ('data_demissao_inicial', models.DateField(blank=True, null=True)),
                ('data_demissao_final', models.DateField(blank=True, null=True)),
                ('rol_separado', models.BooleanField(blank=True, default=False, null=True)),
                ('invalido', models.BooleanField(blank=True, default=False, null=True)),
                ('campo1', models.CharField(choices=[('nome', 'Nome'), ('foto', 'Foto'), ('sexo', 'Sexo'), ('comungante', 'Membro Comungante'), ('categoria', 'Categoria'), ('idade', 'Idade'), ('data_nascimento', 'Aniversário'), ('data_falecimento', 'Data de Falecimento'), ('forma_admissao_pretendida', 'Forma de Admissão Pretendida'), ('estado_civil', 'Estado Civil'), ('estado_civil_complemento', 'Namoro e Noivado'), ('data_inicio_relacionamento', 'Aniversário do Relacionamento'), ('data_pedido_admissao', 'Data do Pedido de Admissao'), ('tem_filhos', 'Tem Filho[s]'), ('rol', 'Rol'), ('forma_admissao', 'Forma de Admissão'), ('data_admissao', 'Data de Admissão'), ('forma_demissao', 'Forma de Demissão'), ('data_demissao', 'Data de Demissão'), ('celular', 'Celular'), ('email', 'Email')], max_length=50)),
                ('campo2', models.CharField(blank=True, choices=[('nome', 'Nome'), ('foto', 'Foto'), ('sexo', 'Sexo'), ('comungante', 'Membro Comungante'), ('categoria', 'Categoria'), ('idade', 'Idade'), ('data_nascimento', 'Aniversário'), ('data_falecimento', 'Data de Falecimento'), ('forma_admissao_pretendida', 'Forma de Admissão Pretendida'), ('estado_civil', 'Estado Civil'), ('estado_civil_complemento', 'Namoro e Noivado'), ('data_inicio_relacionamento', 'Aniversário do Relacionamento'), ('data_pedido_admissao', 'Data do Pedido de Admissao'), ('tem_filhos', 'Tem Filho[s]'), ('rol', 'Rol'), ('forma_admissao', 'Forma de Admissão'), ('data_admissao', 'Data de Admissão'), ('forma_demissao', 'Forma de Demissão'), ('data_demissao', 'Data de Demissão'), ('celular', 'Celular'), ('email', 'Email')], max_length=50, null=True)),
                ('campo3', models.CharField(blank=True, choices=[('nome', 'Nome'), ('foto', 'Foto'), ('sexo', 'Sexo'), ('comungante', 'Membro Comungante'), ('categoria', 'Categoria'), ('idade', 'Idade'), ('data_nascimento', 'Aniversário'), ('data_falecimento', 'Data de Falecimento'), ('forma_admissao_pretendida', 'Forma de Admissão Pretendida'), ('estado_civil', 'Estado Civil'), ('estado_civil_complemento', 'Namoro e Noivado'), ('data_inicio_relacionamento', 'Aniversário do Relacionamento'), ('data_pedido_admissao', 'Data do Pedido de Admissao'), ('tem_filhos', 'Tem Filho[s]'), ('rol', 'Rol'), ('forma_admissao', 'Forma de Admissão'), ('data_admissao', 'Data de Admissão'), ('forma_demissao', 'Forma de Demissão'), ('data_demissao', 'Data de Demissão'), ('celular', 'Celular'), ('email', 'Email')], max_length=50, null=True)),
                ('campo4', models.CharField(blank=True, choices=[('nome', 'Nome'), ('foto', 'Foto'), ('sexo', 'Sexo'), ('comungante', 'Membro Comungante'), ('categoria', 'Categoria'), ('idade', 'Idade'), ('data_nascimento', 'Aniversário'), ('data_falecimento', 'Data de Falecimento'), ('forma_admissao_pretendida', 'Forma de Admissão Pretendida'), ('estado_civil', 'Estado Civil'), ('estado_civil_complemento', 'Namoro e Noivado'), ('data_inicio_relacionamento', 'Aniversário do Relacionamento'), ('data_pedido_admissao', 'Data do Pedido de Admissao'), ('tem_filhos', 'Tem Filho[s]'), ('rol', 'Rol'), ('forma_admissao', 'Forma de Admissão'), ('data_admissao', 'Data de Admissão'), ('forma_demissao', 'Forma de Demissão'), ('data_demissao', 'Data de Demissão'), ('celular', 'Celular'), ('email', 'Email')], max_length=50, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='categorias_relatorio', to='rol.Categoria')),
                ('estados_civis', models.ManyToManyField(blank=True, related_name='estadocivil_relatorio', to='rol.TipoEstadoCivil')),
                ('estados_civis_complementos', models.ManyToManyField(blank=True, related_name='complementoestadocivil_relatorio', to='rol.TipoEstadoCivilComplemento')),
                ('formas_admissao', models.ManyToManyField(blank=True, related_name='formasadmissao_relatorio', to='rol.TipoAdmissao')),
                ('formas_admissao_pretendida', models.ManyToManyField(blank=True, related_name='formaadmissao_relatorio', to='rol.TipoAdmissao')),
                ('formas_demissao', models.ManyToManyField(blank=True, related_name='formasdemissao_relatorio', to='rol.TipoDemissao')),
                ('rols', models.ManyToManyField(blank=True, related_name='rols_relatorio', to='rol.Rol')),
                ('user_update', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='criado_por', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
