# Generated by Django 2.0 on 2019-11-11 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0041_pessoa_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['pk']},
        ),
    ]
