# Generated by Django 2.0 on 2019-11-12 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0042_auto_20191112_1023'),
        ('rol', '0042_auto_20191111_1058'),
    ]

    operations = [
    ]
