# Generated by Django 2.0 on 2020-06-15 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0045_auto_20200414_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='turma_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='turma_grupo_relatorio', to='rol.TurmaFrequencia'),
        ),
    ]
