# Generated by Django 2.0 on 2020-10-08 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0046_relatorio_turma_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTalento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Talento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=256)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='categoria_talento', to='rol.CategoriaTalento')),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='talentos',
            field=models.ManyToManyField(related_name='banco_talentos', to='rol.Talento'),
        ),
    ]
