# Generated by Django 2.0 on 2020-10-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0048_auto_20201019_1619'),
    ]

    operations = [
    ]
