# Generated by Django 2.0 on 2020-10-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0049_merge_20201019_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oficialato',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='oficialato',
            name='ordenacao',
        ),
        migrations.AlterField(
            model_name='oficialato',
            name='cargo_atual',
            field=models.CharField(choices=[('diacono', 'Diácono'), ('diacono_disp', 'Diácono em disponibilidade'), ('pastor_aux', 'Pastor Auxiliar'), ('pastor_evang', 'Pastor Evangelista'), ('pastor_titular', 'Pastor Titular'), ('presbitero', 'Presbítero'), ('presbitero_disp', 'Presbítero em disponibilidade'), ('presb_diac_disp', 'Presbítero/Diácono em disponibilidade'), ('licenciado', 'Licenciado')], max_length=256),
        ),
    ]
